### ISSUE TITLE
Games download not working 

### ISSUE THREAD

**Issue by vegeto10** [finalmakerr/featherence#113]
Can’t download games. could you fix that pls. pls.

**Comment by herogab** [comment]
same  the website do not exist :( im sad as fk the project is very beautiful but the essential feature is missing

**Comment by finalmakerr** [comment]
The downloads failed to work since the free-hosting service was on a quota do to high-demand so when realized I had to unshare it so it's will went off eventually.
To be honest I was amazed to see some of the links are still working so I will do my best to fix what I can for you.


Farewell and enj😄y
